

title: Title
description: This is where I share cool stuff 
author: warmsaft

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: warmsaft
      category: "project"
